module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testMatch: ['<rootDir>/__tests__/**/*.test.ts', '<rootDir>/__tests__/**/*.test.tsx'],
  moduleNameMapper: {
    '^expo-localization$': '<rootDir>/__tests__/mocks/expoLocalization.ts',
    '^firebase/app$': '<rootDir>/__tests__/mocks/firebaseApp.ts',
    '^firebase/auth$': '<rootDir>/__tests__/mocks/firebaseAuth.ts',
    '^@/lib/firebase$': '<rootDir>/__tests__/mocks/firebase.ts',
    '^@/(.*)$': '<rootDir>/$1',
    '^tailwind.config$': '<rootDir>/tailwind.config.js',
  },
  collectCoverageFrom: [
    'app/**/*.{ts,tsx}',
    'components/**/*.{ts,tsx}',
    'constants/**/*.{ts,tsx}',
    'contexts/**/*.{ts,tsx}',
    'hooks/**/*.{ts,tsx}',
    'i18n/**/*.{ts,tsx}',
    'lib/**/*.{ts,tsx}',
    '!app/**',
    '!components/views/**',
    '!components/ui/**',
    '!components/auth/Login.tsx',
    '!components/auth/RegisterForm.tsx',
    '!components/dashboard/RadarMapCard.tsx',
    '!components/haptic-tab.tsx',
    '!components/overlays/PdfPreviewFrame.tsx',
    '!hooks/use-color-scheme.ts',
    '!hooks/use-color-scheme.web.ts',
    '!**/*.stories.{ts,tsx}',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!**/*.config.{ts,js,mjs}',
    '!components/ui/gluestack-ui-provider/**',
    '!components/**/types.ts',
    '!components/**/index.ts',
    '!lib/firebase.ts',
    '!lib/queryClient.tsx',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/cypress/',
    '/stories/',
    '/assets/',
    '/dist/',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?|expo|expo-modules-core|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|@react-native-async-storage/async-storage)/)',
  ],
};
