sonar.projectKey=vitrorin_StatuScope-FrontEnd
sonar.organization=vitrorin

sonar.projectName=StatuScope Frontend
sonar.projectVersion=1.0.0

sonar.sources=app,components,contexts,hooks,lib
sonar.exclusions=node_modules/**,dist/**,coverage/**,__tests__/**,stories/**,.storybook/**

sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
